FROM python:3.11-slim

WORKDIR /app

COPY server.py /app/server.py
COPY requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir -r /app/requirements.txt

EXPOSE 5000
CMD ["python", "server.py"]
